# 인덱싱n슬라이싱 
- 배열의 범위에서 벗어나는 인덱싱과 슬라이싱

## python list에 대해

### 인덱싱: 크기 n의 list의 경우 -n ~ n-1 에 대해서 에러 안남
- IndexError: list index out of range

In [21]:
li

[3, 5, 3, 1]

In [29]:
for i in range(-10, 10):
    try:
        print(i, li[i])
    except:
        print(f'error for {i}')

error for -10
error for -9
error for -8
error for -7
error for -6
error for -5
-4 3
-3 5
-2 3
-1 1
0 3
1 5
2 3
3 1
error for 4
error for 5
error for 6
error for 7
error for 8
error for 9


### 슬라이싱 : 에러를 내는 방법이 없는 것 같다..!

In [3]:
li = [3, 5, 3, 1]

In [32]:
for i in range(1, -6, -1):
    print(i, li[:i])

1 [3]
0 []
-1 [3, 5, 3]
-2 [3, 5]
-3 [3]
-4 []
-5 []


In [33]:
for i in range(3, 8):
    print(i, li[i:])

3 [1]
4 []
5 []
6 []
7 []


In [17]:
li[3:1]

[]

In [18]:
li[3:3]

[]

In [35]:
li

[3, 5, 3, 1]

In [38]:
(li+[2])[-2::-1]

[1, 3, 5, 3]

In [34]:
li[-3:-2]

[5]

## numpy array에 대해

In [1]:
import numpy as np

In [28]:
arr = np.array(li)
arr

array([3, 5, 3, 1])

### 인덱싱: list와 마찬가지

In [30]:
for i in range(-10, 10):
    try:
        print(i, arr[i])
    except:
        print(f'error for {i}')

error for -10
error for -9
error for -8
error for -7
error for -6
error for -5
-4 3
-3 5
-2 3
-1 1
0 3
1 5
2 3
3 1
error for 4
error for 5
error for 6
error for 7
error for 8
error for 9


### 슬라이싱 : list와 마찬가지

In [39]:
arr

array([3, 5, 3, 1])

In [32]:
for i in range(1, -6, -1):
    print(i, arr[:i])

1 [3]
0 []
-1 [3, 5, 3]
-2 [3, 5]
-3 [3]
-4 []
-5 []


In [40]:
for i in range(3, 8):
    print(i, arr[i:])

3 [1]
4 []
5 []
6 []
7 []


In [41]:
arr[3:1]

array([], dtype=int32)

In [42]:
arr[3:3]

array([], dtype=int32)

In [43]:
arr

array([3, 5, 3, 1])

In [45]:
arr1 = np.append(arr, np.array([2, 3]))

- np.append는 배열+ 배열 개념. list.append와 다름

In [47]:
arr1

array([3, 5, 3, 1, 2, 3])

In [46]:
arr1[-2::-1]

array([2, 1, 3, 5, 3])

In [49]:
arr1[-3:-2]

array([1])

## pandas series에 대해

In [141]:
import pandas as pd

In [142]:
li1 = li + [2, 8]
len(li1), li1

(6, [3, 5, 3, 1, 2, 8])

In [143]:
sr = pd.Series(li1, index=list('CDEFGH'), name='ind_sli' )

In [144]:
sr

C    3
D    5
E    3
F    1
G    2
H    8
Name: ind_sli, dtype: int64

### 인덱싱 : list와 같다

#### sr[n] : number

- IndexError: index 7 is out of bounds for axis 0 with size 6

In [70]:
print(f'len : {len(sr)}\n')
for i in range(-10, 10):
    try:
        print(i, sr[i])
    except:
        print(f'error for {i}')

len : 6

error for -10
error for -9
error for -8
error for -7
-6 3
-5 5
-4 3
-3 1
-2 2
-1 8
0 3
1 5
2 3
3 1
4 2
5 8
error for 6
error for 7
error for 8
error for 9


#### sr.iloc[n] : number

In [71]:
print(f'len : {len(sr)}\n')
for i in range(-10, 10):
    try:
        print(i, sr.iloc[i])
    except:
        print(f'error for {i}')

len : 6

error for -10
error for -9
error for -8
error for -7
-6 3
-5 5
-4 3
-3 1
-2 2
-1 8
0 3
1 5
2 3
3 1
4 2
5 8
error for 6
error for 7
error for 8
error for 9


#### sr.loc[index_name]

In [73]:
print(f'len : {len(sr)}\n')
for i in list('ABCDEFGHIJ'):
    try:
        print(i, sr.loc[i])
    except:
        print(f'error for {i}')

len : 6

error for A
error for B
C 3
D 5
E 3
F 1
G 2
H 8
error for I
error for J


### 슬라이싱

#### sr[::]

In [74]:
sr

C    3
D    5
E    3
F    1
G    2
H    8
Name: ind_sli, dtype: int64

In [80]:
for i in range(1, -8, -1):
    print(i, sr[:i].values)

1 [3]
0 []
-1 [3 5 3 1 2]
-2 [3 5 3 1]
-3 [3 5 3]
-4 [3 5]
-5 [3]
-6 []
-7 []


In [84]:
for i in range(2, 10):
    print(i, sr[i:].values)

2 [3 1 2 8]
3 [1 2 8]
4 [2 8]
5 [8]
6 []
7 []
8 []
9 []


In [85]:
sr[3:1]

Series([], Name: ind_sli, dtype: int64)

In [86]:
sr[3:3]

Series([], Name: ind_sli, dtype: int64)

- np.append는 배열+ 배열 개념. list.append와 다름

In [87]:
sr[-2::-1]

G    2
F    1
E    3
D    5
C    3
Name: ind_sli, dtype: int64

In [88]:
sr[-3:-2]

F    1
Name: ind_sli, dtype: int64

#### sr.iloc[::]

In [89]:
sr

C    3
D    5
E    3
F    1
G    2
H    8
Name: ind_sli, dtype: int64

In [90]:
for i in range(1, -8, -1):
    print(i, sr.iloc[:i].values)

1 [3]
0 []
-1 [3 5 3 1 2]
-2 [3 5 3 1]
-3 [3 5 3]
-4 [3 5]
-5 [3]
-6 []
-7 []


In [91]:
for i in range(2, 10):
    print(i, sr.iloc[i:].values)

2 [3 1 2 8]
3 [1 2 8]
4 [2 8]
5 [8]
6 []
7 []
8 []
9 []


In [92]:
sr.iloc[3:1]

Series([], Name: ind_sli, dtype: int64)

In [93]:
sr.iloc[3:3]

Series([], Name: ind_sli, dtype: int64)

In [94]:
sr.iloc[-2::-1]

G    2
F    1
E    3
D    5
C    3
Name: ind_sli, dtype: int64

In [95]:
sr.iloc[-3:-2]

F    1
Name: ind_sli, dtype: int64

#### sr.loc[::]

In [98]:
sr

C    3
D    5
E    3
F    1
G    2
H    8
Name: ind_sli, dtype: int64

In [97]:
print(f'len : {len(sr)}\n')
for i in list('ABCDEFGHIJ'):
    try:
        print(i, sr.loc[:i].values)
    except:
        print(f'error for {i}')

len : 6

A []
B []
C [3]
D [3 5]
E [3 5 3]
F [3 5 3 1]
G [3 5 3 1 2]
H [3 5 3 1 2 8]
I [3 5 3 1 2 8]
J [3 5 3 1 2 8]


In [99]:
print(f'len : {len(sr)}\n')
for i in list('ABCDEFGHIJ'):
    try:
        print(i, sr.loc[i:].values)
    except:
        print(f'error for {i}')

len : 6

A [3 5 3 1 2 8]
B [3 5 3 1 2 8]
C [3 5 3 1 2 8]
D [5 3 1 2 8]
E [3 1 2 8]
F [1 2 8]
G [2 8]
H [8]
I []
J []


- B가 C보다 작다, I가 H보다 크다라는 것을 임의로 파이썬이 판단 하고있다.


In [100]:
print(f'len : {len(sr)}\n')
for i in list('IJCDEFGHAB'):
    try:
        print(i, sr.loc[:i].values)
    except:
        print(f'error for {i}')

len : 6

I [3 5 3 1 2 8]
J [3 5 3 1 2 8]
C [3]
D [3 5]
E [3 5 3]
F [3 5 3 1]
G [3 5 3 1 2]
H [3 5 3 1 2 8]
A []
B []


# sr.loc[::] 문자 인덱스 슬라이싱
- 인덱스 네임을 무작위로 변경

- ascii 코드 기준으로 작은거 -> 큰거,
- +1 씩 증가해야함,
-  51 52 53 97 98 99 이런식으로 가능

## 무작위 인덱스

In [145]:
sr

C    3
D    5
E    3
F    1
G    2
H    8
Name: ind_sli, dtype: int64

In [146]:
sr.rename(index=dict(zip(sr.index, list('31aAcT'))), inplace=True)

In [147]:
sr

3    3
1    5
a    3
A    1
c    2
T    8
Name: ind_sli, dtype: int64

In [148]:
idx = ['0', '2'] + list(sr.index) + ['U']

In [149]:
print(f'len : {len(sr)}\n')
for i in idx:
    try:
        print(i, sr.loc[i:].values)
    except:
        print(f'error for {i}')

len : 6

error for 0
error for 2
3 [3 5 3 1 2 8]
1 [5 3 1 2 8]
a [3 1 2 8]
A [1 2 8]
c [2 8]
T [8]
error for U


## 정렬된 숫자 + 정렬된 알파벳

In [150]:
sr

3    3
1    5
a    3
A    1
c    2
T    8
Name: ind_sli, dtype: int64

In [151]:
sr.rename(index=dict(zip(sr.index, list('345abc'))), inplace=True)

In [152]:
idx = ['1', '2'] + list(sr.index) + ['d', 'e']

In [153]:
print(f'len : {len(sr)}\n')
for i in idx:
    try:
        print(i, sr.loc[i:].values)
    except:
        print(f'error for {i}')

len : 6

1 [3 5 3 1 2 8]
2 [3 5 3 1 2 8]
3 [3 5 3 1 2 8]
4 [5 3 1 2 8]
5 [3 1 2 8]
a [1 2 8]
b [2 8]
c [8]
d []
e []


In [169]:
for i in list('345abc'):
    print(ord(i))

51
52
53
97
98
99


In [154]:
sr

3    3
4    5
5    3
a    1
b    2
c    8
Name: ind_sli, dtype: int64

## 정렬된 것 중간에 순서 다른 거 끼우기

In [191]:
ord('_'), chr(37)

(95, '%')

In [192]:
li1 = li + [2, 8]
len(li1), li1

(6, [3, 5, 3, 1, 2, 8])

In [193]:
sr = pd.Series(li1, index=list('CDEFGH'), name='ind_sli' )

In [194]:
sr.rename(index=dict(zip(sr.index, list('34%_cd'))), inplace=True)

In [195]:
idx = ['1', '2'] + list(sr.index) + ['e', 'f']

In [196]:
print(f'len : {len(sr)}\n')
for i in idx:
    try:
        print(i, sr.loc[i:].values)
    except:
        print(f'error for {i}')

len : 6

error for 1
error for 2
3 [3 5 3 1 2 8]
4 [5 3 1 2 8]
% [3 1 2 8]
_ [1 2 8]
c [2 8]
d [8]
error for e
error for f


## 정렬된 것 중간에 순서 맞는 거 끼우기

In [197]:
ord('_'), chr(37)

(95, '%')

In [198]:
li1 = li + [2, 8]
len(li1), li1

(6, [3, 5, 3, 1, 2, 8])

In [199]:
sr = pd.Series(li1, index=list('CDEFGH'), name='ind_sli' )

In [200]:
sr.rename(index=dict(zip(sr.index, list('34__cd'))), inplace=True)

In [201]:
idx = ['1', '2'] + list(sr.index) + ['e', 'f']

In [202]:
print(f'len : {len(sr)}\n')
for i in idx:
    try:
        print(i, sr.loc[i:].values)
    except:
        print(f'error for {i}')

len : 6

1 [3 5 3 1 2 8]
2 [3 5 3 1 2 8]
3 [3 5 3 1 2 8]
4 [5 3 1 2 8]
_ [3 1 2 8]
_ [3 1 2 8]
c [2 8]
d [8]
e []
f []


## 간격을 2이상으로 둠

In [208]:
li1 = li + [2, 8]
len(li1), li1

(6, [3, 5, 3, 1, 2, 8])

In [209]:
sr = pd.Series(li1, index=list('CDEFGH'), name='ind_sli' )

In [210]:
sr.rename(index=dict(zip(sr.index, list('68adgj'))), inplace=True)

In [211]:
idx = ['2', '4'] + list(sr.index) + ['m']

In [212]:
print(f'len : {len(sr)}\n')
for i in idx:
    try:
        print(i, sr.loc[i:].values)
    except:
        print(f'error for {i}')

len : 6

2 [3 5 3 1 2 8]
4 [3 5 3 1 2 8]
6 [3 5 3 1 2 8]
8 [5 3 1 2 8]
a [3 1 2 8]
d [1 2 8]
g [2 8]
j [8]
m []


# sr[ ] 과 sr.iloc[]의 차이